### PR TITLE
parse conffiles from the DEBIAN folder

### PR DESCRIPTION
**Pull request by witokondoria**
There wont be a need to keep a RPM symlink

### CODE REVIEW

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request closed without merging**
